### ISSUE TITLE
Getting the following error on app run

### ISSUE THREAD

**Issue by Noman-Khan7** [udacity/ud845-Pets#23]
when i am running app on device ,it is getting crashed with these errors.

06-15 12:07:00.617 17522-17522/com.example.android.pets E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.example.android.pets, PID: 17522
                                                                          java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.android.pets/com.example.android.pets.CatalogActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.android.pets.CatalogActivity" on path: DexPathList[[zip file "/data/app/com.example.android.pets-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.pets-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2384)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
                                                                              at android.app.ActivityThread.access$1100(ActivityThread.java:154)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5582)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.android.pets.CatalogActivity" on path: DexPathList[[zip file "/data/app/com.example.android.pets-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.pets-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                              at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2374)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535) 
                                                                              at android.app.ActivityThread.access$1100(ActivityThread.java:154) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5582) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                          	Suppressed: java.lang.NoClassDefFoundError: com.example.android.pets.CatalogActivity
                                                                              at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                              at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                              at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                              at dalvik.system.DexPathList.findClass(DexPathList.java:338)
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                              		... 13 more
                                                                          	Suppressed: java.lang.ClassNotFoundException: com.example.android.pets.CatalogActivity
                                                                              at java.lang.Class.classForName(Native Method)
                                                                              at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                              at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                              		... 12 more
                                                                           Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
06-15 12:08:48.653 17522-17522/? I/Process: Sending signal. PID: 17522 SIG: 9

**Comment by ash-kamrip** [comment]
i dont think this is anyway related to the code .its some other thing try again importing the source code provided by udacity

**Comment by jay9297** [comment]
Getting the same errors after following through Lesson 3. Any solutions to this?

**Comment by rajatnaik12** [comment]
Check this stackoverflow. https://stackoverflow.com/questions/17973970/how-to-solve-java-lang-noclassdeffounderror

**Comment by SudKul** [comment]
We have upgraded the code to AndroidX in this [commit](https://github.com/udacity/ud845-Pets/commit/942175e9bde6edcd7621d01ec7994b0f6161aeb9). 

We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
